# Generated by Django 5.0.4 on 2024-05-03 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_article_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 3, 17, 28, 51, 167855)
            ),
        ),
    ]
