# Generated by Django 5.0.4 on 2024-05-03 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_article_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
