# Generated by Django 5.0.4 on 2024-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
