# Generated by Django 5.0.4 on 2024-05-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_person_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="website_address",
            field=models.URLField(default=""),
        ),
    ]
