# Generated by Django 5.0.4 on 2024-05-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_person_website_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
