# Generated by Django 5.0.4 on 2024-05-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_article_updated_date_alter_article_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="blog.person"
            ),
            preserve_default=False,
        ),
    ]
