# Generated by Django 5.0.4 on 2024-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
